### ISSUE TITLE
get_current_user() returns RecursionError  

### ISSUE THREAD

**Issue by iamMHZ** [nebstrebor/django-threadlocals#13]
For retrieving the current user, it always returns ` RecursionError`.
Does anybody have any idea?

**Comment by jdkirkwood** [comment]
Do you mean `RecursionError`? That might be related to your own code calling `get_currrent_user()` repeatedly?

**Comment by iamMHZ** [comment]
@jdkirkwood  yeah right, sorry for the typo...
No, I am just calling it in the UserManager that I customized with no loops and no recursive calls.
